#!/usr/bin/env php
<?php

set_time_limit(0);

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Groovey\Config\Providers\ConfigServiceProvider;
use Groovey\Tester\Providers\TesterServiceProvider;


$app = new Application();

$app->addCommands([
        new Groovey\Backup\Commands\About(),


    ]);

$status = $app->run();

exit($status);
